import os 
import secrets
from pathlib import Path

CONFIG_DIR = Path.home() / ".psamvault"
CONFIG_FILE = CONFIG_DIR / "config.env"


REQUIRED_KEYS = ["PSAMVAULT_API_URL", "PSAMVAULT_PEPPER"]

DEFAULT_API_URL = "https://psam-vault-backend.onrender.com"

def generate_pepper() -> str:
    """
    Generate a cryptographically secure 64-character hex pepper.
 
    The pepper is unique per user/device. It is combined with the login
    password via HMAC-SHA256 to produce the master password, ensuring
    that even if two users share the same login password their vault
    encryption keys are completely different.
 
    Returns:
        A 64-character hex string — 32 random bytes encoded as hex.
    """
    return secrets.token_hex(32)



def load_config() -> None:
    """
    Load config from ~/.psamvault/config.env into os.environ so that
    api_client.py and crypto.py pick them up via os.getenv().
 
    Called once at startup in main.py before any command runs.
    Does nothing if the config file does not exist yet — the configure
    command will create it.
    """
    
    if not CONFIG_FILE.exists():
        return
    
    for line in CONFIG_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        # Only set if not already set by a real environment variable —
        # real env vars always take precedence over the config file
        if key and value and key not in os.environ:
            os.environ[key] = value
            

        
def save_config(api_url: str, pepper: str) -> None:
    """
    Write PSAMVAULT_API_URL and PSAMVAULT_PEPPER to
    ~/.psamvault/config.env with restricted permissions (600).
 
    Args:
        api_url: The base URL of the psamvault backend API.
        pepper:  The HMAC pepper used to derive the master password.
    """
    CONFIG_DIR.mkdir(mode=0o700, parents=True, exist_ok=True)
    
    content = (
        "# psamvault configuration\n"
        "# Generated by  psamvault configure\n"
        "# Do not share this file — it contains your pepper value.\n"
        "\n"
        f"PSAMVAULT_API_URL={api_url}\n"
        f"PSAMVAULT_PEPPER={pepper}\n"
    )
    
    CONFIG_FILE.write_text(content)
    os.chmod(CONFIG_FILE, 0o600)
    

def is_configured() -> bool:
    """
    Return True if both required config values are available —
    either from the config file or from real environment variables.
    """
    load_config()
    return all(os.getenv(k) for k in REQUIRED_KEYS)


def get_config() -> dict:
    """
    Return the current config values as a dict.
    Loads the config file first so values are always fresh.
    """
    load_config()
    return {k: os.getenv(k, "") for k in REQUIRED_KEYS}
    
    